In [55]:
import pandas as pd
import numpy as np
import os
import h5py

In [56]:
pip install geopandas

Requirement already satisfied: geopandas in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (0.8.1)
Requirement already satisfied: shapely in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from geopandas) (1.7.1)
Requirement already satisfied: fiona in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from geopandas) (1.8.18)
Requirement already satisfied: pandas>=0.23.0 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from geopandas) (1.1.4)
Requirement already satisfied: pyproj>=2.2.0 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from geopandas) (3.0.0.post1)
Requirement already satisfied: munch in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from fiona->geopandas) (2.5.0)
Requirement already satisfied: click-plugins>=1.0 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from fiona->geopandas) (1.1.1)
Requirement already satisfied: certifi in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from fiona->geopandas) (2020.6.20)
Requirement already satisfied: six>=1.7 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from fiona->geopandas) (1.15.0)
Requirement already satisfied: attrs>=17 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from fiona->geopandas) (19.3.0)
Requirement already satisfied: click<8,>=4.0 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from fiona->geopandas) (7.1.2)
Requirement already satisfied: cligj>=0.5 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from fiona->geopandas) (0.7.1)
Requirement already satisfied: numpy>=1.15.4 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.23.0->geopandas) (1.19.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.23.0->geopandas) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.23.0->geopandas) (2020.1)
Note: you may need to restart the kernel to use updated packages.

In [57]:
pip install osmnx

Requirement already satisfied: osmnx in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (0.16.2)
Requirement already satisfied: matplotlib>=3.3 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from osmnx) (3.3.3)
Requirement already satisfied: descartes>=1.1 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from osmnx) (1.1.0)
Requirement already satisfied: geopandas>=0.8 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from osmnx) (0.8.1)
Requirement already satisfied: networkx>=2.5 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from osmnx) (2.5)
Requirement already satisfied: pandas>=1.1 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from osmnx) (1.1.4)
Requirement already satisfied: Rtree>=0.9 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from osmnx) (0.9.4)
Requirement already satisfied: pyproj>=2.6 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from osmnx) (3.0.0.post1)
Requirement already satisfied: numpy>=1.19 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from osmnx) (1.19.4)
Requirement already satisfied: Shapely>=1.7 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from osmnx) (1.7.1)
Requirement already satisfied: requests>=2.24 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from osmnx) (2.24.0)
Requirement already satisfied: pillow>=6.2.0 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.3->osmnx) (7.2.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.3->osmnx) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.3->osmnx) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.3->osmnx) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.3->osmnx) (2.8.1)
Requirement already satisfied: fiona in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from geopandas>=0.8->osmnx) (1.8.18)
Requirement already satisfied: decorator>=4.3.0 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from networkx>=2.5->osmnx) (4.4.2)
Requirement already satisfied: pytz>=2017.2 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from pandas>=1.1->osmnx) (2020.1)
Requirement already satisfied: setuptools in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from Rtree>=0.9->osmnx) (49.2.0.post20200714)
Requirement already satisfied: certifi in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from pyproj>=2.6->osmnx) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.24->osmnx) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.24->osmnx) (1.25.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.24->osmnx) (3.0.4)
Requirement already satisfied: six in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from cycler>=0.10->matplotlib>=3.3->osmnx) (1.15.0)
Requirement already satisfied: munch in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from fiona->geopandas>=0.8->osmnx) (2.5.0)
Requirement already satisfied: click<8,>=4.0 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from fiona->geopandas>=0.8->osmnx) (7.1.2)
Requirement already satisfied: cligj>=0.5 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from fiona->geopandas>=0.8->osmnx) (0.7.1)
Requirement already satisfied: click-plugins>=1.0 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from fiona->geopandas>=0.8->osmnx) (1.1.1)
Requirement already satisfied: attrs>=17 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from fiona->geopandas>=0.8->osmnx) (19.3.0)
Note: you may need to restart the kernel to use updated packages.

In [58]:
# geography
import geopandas as gpd
import osmnx as ox
import csv

In [169]:
df = pd.read_csv('/Users/katiecason/Desktop/207_folder/w207_finalproject/data/tweets_csv/april1_april2.csv')

In [62]:
pip install geopy

Requirement already satisfied: geopy in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (2.0.0)
Requirement already satisfied: geographiclib<2,>=1.49 in /Users/katiecason/opt/anaconda3/lib/python3.8/site-packages (from geopy) (1.50)
Note: you may need to restart the kernel to use updated packages.

In [63]:
from geopy.geocoders import Nominatim
from geopy.point import Point

In [170]:
#manually filtering latitude and longitude to find locations

df = df[df['coordinates'].notna()]
data = df['coordinates'].str.split(',', n=1, expand = True)
df['longitude'] = data[0]
df['latitude'] = data[1]
df['coordinates'] = df[['latitude', 'longitude']].apply(lambda x: ','.join(x), axis=1)

In [171]:
geolocator = Nominatim(user_agent='katiecason@berkeley.edu')
location = df['coordinates'].apply(lambda x: geolocator.reverse(x))

In [172]:
states = location.apply(lambda x: x.raw['address'].get('state', ''))

In [173]:
df['state'] = states

In [174]:
df

,coordinates,created_at,hashtags,media,urls,favorite_count,id,in_reply_to_screen_name,in_reply_to_status_id,in_reply_to_user_id,...,user_location,user_name,user_screen_name.1,user_statuses_count,user_time_zone,user_urls,user_verified,longitude,latitude,state
0,"-1.29889,36.77943",Wed Apr 01 09:01:18 +0000 2020,corona coronavirus covid stayhome,NaN,https://www.instagram.com/p/B-brG4pFTdp/?igshi...,0,1245275030956544002,NaN,NaN,NaN,...,"EAST AFRICA, WORLDWIDE",NDANAH MIQASSA,bandanahmiqassa,23042,NaN,https://youtu.be/0uu8AzxGmeI,False,36.77943,-1.29889,Nairobi
1,"49.64968784,6.12745379",Wed Apr 01 08:17:02 +0000 2020,actufoot football luxembourg,NaN,http://dlvr.it/RSy1bQ,0,1245263893682769921,NaN,NaN,NaN,...,Luxembourg,FuPa Luxembourg,fupalux,6243,NaN,http://www.fupa.net/luxemburg,False,6.12745379,49.64968784,
2,"51.2334699,-0.32863",Wed Apr 01 09:01:11 +0000 2020,homeschooling stayhome corona,NaN,https://www.instagram.com/p/B-brXf-hhna/?igshi...,0,1245275001563099136,NaN,NaN,NaN,...,NaN,Emilie-Kate Owen,emiliekateowen,236,NaN,NaN,False,-0.32863,51.2334699,England
3,"43.648,-79.3872",Wed Apr 01 10:04:31 +0000 2020,comedian comedy funny,NaN,https://www.instagram.com/p/B-byRhlHij9/?igshi...,0,1245290940148875265,NaN,NaN,NaN,...,"Toronto,NewYork,LosAngeles,MIA",KingOfScotia,SoFlyyTizzy902,11637,NaN,NaN,False,-79.3872,43.648,Ontario
4,"42.4969,18.4503",Wed Apr 01 08:48:05 +0000 2020,stayhome staysafe stayhealthy corona covid cov...,NaN,https://www.instagram.com/p/B-bp3RaIgii/?igshi...,0,1245271705804771328,NaN,NaN,NaN,...,NaN,ellen schepens,ellenschepens,1587,NaN,http://www.ellenschepens.com,False,18.4503,42.4969,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586,"13.67087,79.04951",Thu Apr 02 06:25:53 +0000 2020,NaN,NaN,https://www.instagram.com/p/B-d-ZGUDFc1/?igshi...,0,1245598309328117761,NaN,NaN,NaN,...,"Andhra Pradesh, India",M S Imran Jkmsf,msimran4462,70,NaN,NaN,False,79.04951,13.67087,Andhra Pradesh
587,"-27.75,29.9333",Thu Apr 02 06:25:49 +0000 2020,NaN,NaN,https://www.instagram.com/p/B-d-YiDDB76/?igshi...,0,1245598290940289026,NaN,NaN,NaN,...,"Newcastle, South Africa",Peter Mushoriwa,mushoriwapeter,36,NaN,NaN,False,29.9333,-27.75,KwaZulu-Natal
588,"31.13570968,-7.91885142",Thu Apr 02 06:15:36 +0000 2020,NaN,NaN,https://www.instagram.com/p/B-d9NPfp95N/?igshi...,6,1245595719076990976,NaN,NaN,NaN,...,The Atlas Expedition,alice morrison,aliceoutthere1,7725,NaN,http://www.alicemorrison.co.uk/podcast,False,-7.91885142,31.13570968,
589,"11.256405,75.785708",Thu Apr 02 06:29:27 +0000 2020,gocorona TheTower StaySafe stayhome stayhealth...,NaN,http://ubaid.ck https://www.instagram.com/p/B-...,0,1245599205298556929,NaN,NaN,NaN,...,#Vengara #Kozhikode #Kerala,❤ Tagliafico ⚽,zainukappan,46932,NaN,NaN,False,75.785708,11.256405,Kerala
590,"9.53580482,99.93404734",Thu Apr 02 06:33:00 +0000 2020,corona archive thailand kohsamui,NaN,https://www.instagram.com/p/B-d_NJ1JOxH/?igshi...,3,1245600097708019712,NaN,NaN,NaN,...,"Moscow, Russia",leyli Karimova,leylikarimova,51407,NaN,http://www.instagram.com/leyli.karimova,False,99.93404734,9.53580482,จังหวัดสุราษฎร์ธานี

In [175]:
df = df[df.state != '']

In [176]:
df

,coordinates,created_at,hashtags,media,urls,favorite_count,id,in_reply_to_screen_name,in_reply_to_status_id,in_reply_to_user_id,...,user_location,user_name,user_screen_name.1,user_statuses_count,user_time_zone,user_urls,user_verified,longitude,latitude,state
0,"-1.29889,36.77943",Wed Apr 01 09:01:18 +0000 2020,corona coronavirus covid stayhome,NaN,https://www.instagram.com/p/B-brG4pFTdp/?igshi...,0,1245275030956544002,NaN,NaN,NaN,...,"EAST AFRICA, WORLDWIDE",NDANAH MIQASSA,bandanahmiqassa,23042,NaN,https://youtu.be/0uu8AzxGmeI,False,36.77943,-1.29889,Nairobi
2,"51.2334699,-0.32863",Wed Apr 01 09:01:11 +0000 2020,homeschooling stayhome corona,NaN,https://www.instagram.com/p/B-brXf-hhna/?igshi...,0,1245275001563099136,NaN,NaN,NaN,...,NaN,Emilie-Kate Owen,emiliekateowen,236,NaN,NaN,False,-0.32863,51.2334699,England
3,"43.648,-79.3872",Wed Apr 01 10:04:31 +0000 2020,comedian comedy funny,NaN,https://www.instagram.com/p/B-byRhlHij9/?igshi...,0,1245290940148875265,NaN,NaN,NaN,...,"Toronto,NewYork,LosAngeles,MIA",KingOfScotia,SoFlyyTizzy902,11637,NaN,NaN,False,-79.3872,43.648,Ontario
6,"51.51013381,-0.08604754",Wed Apr 01 05:46:58 +0000 2020,London underground corona commute covid19 soci...,NaN,https://www.instagram.com/p/B-bVJGIgJq8/?igshi...,0,1245226125636317184,NaN,NaN,NaN,...,City of London,🌱 Charles Pycraft 📷,yiquai,36839,NaN,http://www.pycraftgardening.co.uk,False,-0.08604754,51.51013381,England
7,"28.631747,77.219672",Wed Apr 01 06:29:55 +0000 2020,mavic2pro mavic dji,NaN,https://www.instagram.com/p/B-baDo1Aaas/?igshi...,0,1245236933711867905,NaN,NaN,NaN,...,NaN,Gourav arya,Cinematorseye,176,NaN,NaN,False,77.219672,28.631747,Delhi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,"22.7253,75.8655",Thu Apr 02 06:17:33 +0000 2020,NaN,NaN,https://www.instagram.com/p/B-d9X9cnhuT/?igshi...,1,1245596210578083845,NaN,NaN,NaN,...,"Mumbai, India",Viral Bhayani,viralbhayani77,32199,NaN,NaN,False,75.8655,22.7253,Madhya Pradesh
586,"13.67087,79.04951",Thu Apr 02 06:25:53 +0000 2020,NaN,NaN,https://www.instagram.com/p/B-d-ZGUDFc1/?igshi...,0,1245598309328117761,NaN,NaN,NaN,...,"Andhra Pradesh, India",M S Imran Jkmsf,msimran4462,70,NaN,NaN,False,79.04951,13.67087,Andhra Pradesh
587,"-27.75,29.9333",Thu Apr 02 06:25:49 +0000 2020,NaN,NaN,https://www.instagram.com/p/B-d-YiDDB76/?igshi...,0,1245598290940289026,NaN,NaN,NaN,...,"Newcastle, South Africa",Peter Mushoriwa,mushoriwapeter,36,NaN,NaN,False,29.9333,-27.75,KwaZulu-Natal
589,"11.256405,75.785708",Thu Apr 02 06:29:27 +0000 2020,gocorona TheTower StaySafe stayhome stayhealth...,NaN,http://ubaid.ck https://www.instagram.com/p/B-...,0,1245599205298556929,NaN,NaN,NaN,...,#Vengara #Kozhikode #Kerala,❤ Tagliafico ⚽,zainukappan,46932,NaN,NaN,False,75.785708,11.256405,Kerala
590,"9.53580482,99.93404734",Thu Apr 02 06:33:00 +0000 2020,corona archive thailand kohsamui,NaN,https://www.instagram.com/p/B-d_NJ1JOxH/?igshi...,3,1245600097708019712,NaN,NaN,NaN,...,"Moscow, Russia",leyli Karimova,leylikarimova,51407,NaN,http://www.instagram.com/leyli.karimova,False,99.93404734,9.53580482,จังหวัดสุราษฎร์ธานี

In [177]:
items_counts = df['state'].value_counts()
max_county = items_counts.idxmax()
items_counts

California             66
England                50
New York               41
Florida                22
Texas                  19
                       ..
Nusa Tenggara Timur     1
المنطقة الشرقية         1
සබරගමුව පළාත            1
Idaho                   1
Lombardia               1
Name: state, Length: 144, dtype: int64